#! /bin/sh

cat >&2 <<EOF

	Upstream changed the name of the program binary to 'engauge'.
	This Debian wrapper will invoke 'engauge' for you this time.
	The wrapper will go away in the release after lenny.

EOF

sleep 1

exec /usr/bin/engauge "$@"
